### ISSUE TITLE
high level architecture part in manual

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tfgridsdk#12]
can use pictures from

https://docs.google.com/presentation/d/1yA__jH9ZqAXXi8ORezAiDp_mebnt89fWNmEAQQzyJOg/edit

- [General](https://github.com/threefoldfoundation/info_tfgridsdk/issues/34)
- [Storage](https://github.com/threefoldfoundation/info_tfgridsdk/issues/33)

Primitves:
- [x] General
- [x] Network
- [ ]  Webgateway
- [x] Storage
- [x] boot
- [x] flists

**Comment by weynandkuijpers** [comment]
Network done [(here)](https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/intro/architecture_network.md)
