### ISSUE TITLE
minio-docs: a walk through for deploying full solution using the sdk

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldfoundation/info_tfgridsdk#124]
Current the `minio-docs` branch has a tutorial on how to deploy a fully working master/slave minio setup (plus monitoring)

We need a similar flow but that uses the jumpscale sdk to do this.

This walk through should also have extra steps to:
- How to destroy minio the minio containers and re-create them again with the same zdb and tlog to deploy a new slave or master.

**Comment by muhamadazmy** [comment]
@zaibon 

So, I had a quick discussion about this issue with @rkhamis and we came to the following conclusion. 

- The api only support the primitives
- The "solution" building logic is entirely in the chat-flows
- Writing a tutorial that uses the API to build the full minio solution is gonna be very long and complicated. 
- Who are the audience?
  - The chat flows (with the next button) seems already to confuse a lot of people.
- The tutorial will be a copy of the current chat-flow code!
May be for such advanced users we point them to the chat-flow code instead, since it's open-source.

**Comment by zaibon** [comment]
The target audience is anyone that want to build a business on top of the grid and want to be able to deploy a production grade archive solution using our minio implementation.

The chat flow are example and nobody can build on top. 
If the code of the chat flow is clean and readable enough I have nothing against using it and document it to explain all the steps.

> Writing a tutorial that uses the API to build the full minio solution is gonna be very long and complicated.

If this is the case then this show a bigger problem. Or our tools is crap... or something is not understood cause it should really not be complicated at all...But hearing this from the devs themself... this make me shivers...

**Comment by zaibon** [comment]
There is no reason for the deployment code to be drastically different them what is shown there: https://github.com/threefoldtech/jumpscaleX_libs/tree/development/JumpscaleLibs/sal/zosv2#example--deploy-minio-container. This is code less then 100 line long...
