### ISSUE TITLE
(Manual content) getting started on stellar and wallet

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgridsdk#17]
[getting_started_on_stellar](https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/gettingstarted/getting_on_stellar.md)

Integrate 
- [stellarx info](https://github.com/threefoldfoundation/info_threefold/blob/development/src/docs/token/how_to_buy/stellarx.md)
- [interstellar info](https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/TOADD/peer2peer_storage_compute/setup_guides/prerequisites/tfts-interstellar.md)

**Comment by VonSub** [comment]
have some updated version at info_threefold will do includes from there.
