### ISSUE TITLE
see test page on home: can we see how to integrate webix component?

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tfgridsdk#32]
now the index goes away (the menu left).
can we show webix component without that going away?

basically navigation should be over full page and the widgets more to the right

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/78877200-c340d600-7a50-11ea-8780-144ba9d5c83f.png)

would be incredible we can show these components, would be super easy to make a pre-processor to put rich content in.

**Comment by xmonader** [comment]
@Hamdy what's the status here?
