### ISSUE TITLE
Generic storage architecture description

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgridsdk#33]
https://github.com/threefoldfoundation/info_tfgridsdk/blob/6c62f3a5eb6905cea21a4bb5124259a5398bcbfc/src/intro/architecture_storage.md#L3-L3

**Comment by weynandkuijpers** [comment]
Please read and imrpvie typos and pieces that are hard to understand.

**Comment by VonSub** [comment]
proofread and typo fixed.
