### ISSUE TITLE
Generic architecture description

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgridsdk#34]
https://github.com/threefoldfoundation/info_tfgridsdk/blob/6c62f3a5eb6905cea21a4bb5124259a5398bcbfc/src/intro/architecture.md#L4-L4

**Comment by weynandkuijpers** [comment]
Please read for type and unclear text.

**Comment by weynandkuijpers** [comment]
Please read for type and unclear descriptions

**Comment by VonSub** [comment]
done: https://github.com/threefoldfoundation/info_tfgridsdk/pull/51
