### ISSUE TITLE
Compile and maintain glossary for this manual (cloud.threefold.io) work

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgridsdk#35]
Find source here: https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/glossary.md

**Comment by weynandkuijpers** [comment]
please check for new terms

**Comment by Sacha96** [comment]
looks good! don't get the point-to-point but trust you on this. We're good to go with those terms
