### ISSUE TITLE
document identity management using SDK

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/info_tfgridsdk#40]
Basic information is here: https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Identity.md

**Comment by xmonader** [comment]
Documented reviewed and improved by @despiegk. copied into the manual now
https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/gettingstarted/identity.md

**Comment by despiegk** [comment]
where is the doc now?
