### ISSUE TITLE
Need to have webgateway functionality and description how to user it

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_tfgridsdk#44]

**Comment by xmonader** [comment]
@weynandkuijpers solved here https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/sdk/chat/solutions/webgateway/README.md or still need something more?

**Comment by weynandkuijpers** [comment]
Perfect.  Will pull a copy in the tfgrid mdbook
