### ISSUE TITLE
wizards

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_tfgridsdk#50]
![image](https://user-images.githubusercontent.com/6021844/78987564-b1356500-7b2e-11ea-93c6-0b1c85b26c9b.png)

thabet had documented the chats, I don't find them

also there is a dir wizards and dir chat?
whats the difference

**Comment by xmonader** [comment]
all of them except for gateway solution "will document asap"
https://github.com/threefoldfoundation/info_tfgridsdk/tree/development/src/sdk/chat/solutions

**Comment by xmonader** [comment]
Gateway solution integrated. moving to verification
