### ISSUE TITLE
Applicationserver/Packages: workflow pic missing

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_tfgridsdk#55]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/18591016/79103596-31e1a480-7d6d-11ea-9f7a-9cb4e2861798.png">

**Comment by xmonader** [comment]
@gmachtel was kind enough to fix it https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/sdk/applicationserver/packages.md
