### ISSUE TITLE
SDK/Admin/Extending admin: content missing

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/info_tfgridsdk#56]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/18591016/79104032-03b09480-7d6e-11ea-8553-1f2964b5631a.png">

**Comment by xmonader** [comment]
https://github.com/threefoldfoundation/info_tfgridsdk/blob/development/src/sdk/admin/extending_admin.md
