### ISSUE TITLE
Getting Started Manual - Deploy website [development_deploying_website]

### ISSUE THREAD

**Issue by ranatrk** [threefoldfoundation/info_tfgridsdk#94]
Create a manual with steps to deploy a website from scratch:

**Suggested flow:**
- [x] Package website into an flist (either converting docker image or using jumpscale)
- [x] Deploy a container with the flist created 
- [x] configure web gateway to expose the website over the customer domain

**Comment by zaibon** [comment]
To create an flist, you can also just upload a tar archive to the hub. This is probably the easiest and straight  forward way to do it. `zflist` CLI is also available: https://github.com/threefoldtech/0-flist#zflist

**Comment by ranatrk** [comment]
WIP docs so far  https://github.com/threefoldfoundation/info_tfgridsdk/compare/development_deploying_website?expand=1

**Comment by zaibon** [comment]
https://github.com/threefoldfoundation/info_tfgridsdk/pull/95
